#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BID_Front.Resource", IsApplication=true)]

namespace BID_Front
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bg = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int shape = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060007
			public const int btEmployee = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int btSetting = 2131099656;
			
			// aapt resource value: 0x7f060003
			public const int btntake = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int ivPhoto = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int tableLayout1 = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int textView10 = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int tvCard = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int tvEmail = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int tvName = 2131099653;
			
			// aapt resource value: 0x7f060009
			public const int tvServer = 2131099657;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int employee = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int server = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int cancel = 2130968580;
			
			// aapt resource value: 0x7f040007
			public const int card = 2130968583;
			
			// aapt resource value: 0x7f04000a
			public const int cardhint = 2130968586;
			
			// aapt resource value: 0x7f040003
			public const int confirm = 2130968579;
			
			// aapt resource value: 0x7f040009
			public const int email = 2130968585;
			
			// aapt resource value: 0x7f04000c
			public const int emailhint = 2130968588;
			
			// aapt resource value: 0x7f040008
			public const int name = 2130968584;
			
			// aapt resource value: 0x7f04000b
			public const int namehint = 2130968587;
			
			// aapt resource value: 0x7f040005
			public const int photo = 2130968581;
			
			// aapt resource value: 0x7f040001
			public const int record = 2130968577;
			
			// aapt resource value: 0x7f04000d
			public const int server = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int serverhint = 2130968590;
			
			// aapt resource value: 0x7f040002
			public const int setting = 2130968578;
			
			// aapt resource value: 0x7f040006
			public const int take = 2130968582;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int AppSplash = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int button = 2131034113;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
