#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AppX45.Resource", IsApplication=true)]

namespace AppX45
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Bulbs = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int FlowerBuds = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Fruits = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Legumes = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Tubers = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Vegetables = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070007
			public const int Image = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int List = 2131165192;
			
			// aapt resource value: 0x7f070004
			public const int Text = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int Text1 = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int Text2 = 2131165190;
			
			// aapt resource value: 0x7f07000d
			public const int about = 2131165197;
			
			// aapt resource value: 0x7f070003
			public const int consoleText = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int demoScroller = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int demoTitle = 2131165184;
			
			// aapt resource value: 0x7f07000b
			public const int deviceList = 2131165195;
			
			// aapt resource value: 0x7f07000e
			public const int exit = 2131165198;
			
			// aapt resource value: 0x7f07000a
			public const int progressBar = 2131165194;
			
			// aapt resource value: 0x7f070009
			public const int progressBarTitle = 2131165193;
			
			// aapt resource value: 0x7f070001
			public const int separator = 2131165185;
			
			// aapt resource value: 0x7f07000c
			public const int tt = 2131165196;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int console = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CustomView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int HomeScreen = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int mylistview = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int menu1 = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int refreshing = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int tt = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int immersiveTheme = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
