#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("App1.Resource", IsApplication=true)]

namespace App1
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int anim_slide_in_left = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int anim_slide_out_left = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int fade_in = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int fade_out = 2130968579;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int border = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int face_ysj = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon1 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon2 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon3 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int image = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int on = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int MyButton = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int MyButton1 = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int MyButton2 = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int MyButton4 = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int MyButton5 = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int MyButton6 = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int MyButton7 = 2131165191;
			
			// aapt resource value: 0x7f070001
			public const int MyButtonInit = 2131165185;
			
			// aapt resource value: 0x7f070009
			public const int button1 = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int button2 = 2131165194;
			
			// aapt resource value: 0x7f070008
			public const int imageView1 = 2131165192;
			
			// aapt resource value: 0x7f07000b
			public const int img = 2131165195;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int myimage = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int sub = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Test = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int testTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
