#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("App1.Resource", IsApplication=true)]

namespace App1
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int anim_slide_in_left = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int anim_slide_in_right = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int anim_slide_out_left = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int anim_slide_out_right = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int fade_in = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int fade_out = 2130968581;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int ysj = 2131034112;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int border = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int face_ysj = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon1 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon2 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon3 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int image = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int on = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int red_button = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int son1 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int son2 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int son3 = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080001
			public const int MyButton = 2131230721;
			
			// aapt resource value: 0x7f080003
			public const int MyButton1 = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int MyButton2 = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int MyButton4 = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int MyButton5 = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int MyButton6 = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int MyButton7 = 2131230728;
			
			// aapt resource value: 0x7f080002
			public const int MyButtonInit = 2131230722;
			
			// aapt resource value: 0x7f08000b
			public const int button1 = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int button2 = 2131230732;
			
			// aapt resource value: 0x7f08000d
			public const int button3 = 2131230733;
			
			// aapt resource value: 0x7f08000e
			public const int button4 = 2131230734;
			
			// aapt resource value: 0x7f080009
			public const int imageView1 = 2131230729;
			
			// aapt resource value: 0x7f08000f
			public const int img = 2131230735;
			
			// aapt resource value: 0x7f08000a
			public const int textview1 = 2131230730;
			
			// aapt resource value: 0x7f080000
			public const int viewFlipper1 = 2131230720;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int flipper = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int myimage = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int result = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int sub = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Test = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ysj = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public const int button_text = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int testTheme = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int ysjTheme = 2131165186;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
