#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Android_Demo.Resource", IsApplication=true)]

namespace Android_Demo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int alpha = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int rotate = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int scale = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int translate = 2130968579;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int shape = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int son = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000c
			public const int MyButton = 2131099660;
			
			// aapt resource value: 0x7f060008
			public const int alter = 2131099656;
			
			// aapt resource value: 0x7f06000d
			public const int btnSendSMS1 = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int btnSendSMS2 = 2131099662;
			
			// aapt resource value: 0x7f060002
			public const int buttona = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int buttonalter = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int buttonr = 2131099653;
			
			// aapt resource value: 0x7f060003
			public const int buttons = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int buttont = 2131099652;
			
			// aapt resource value: 0x7f060009
			public const int faceImage = 2131099657;
			
			// aapt resource value: 0x7f060001
			public const int linearLayout1 = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int linearLayout2 = 2131099648;
			
			// aapt resource value: 0x7f060007
			public const int rl = 2131099655;
			
			// aapt resource value: 0x7f06000b
			public const int tvName = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int tvWecomeEmp = 2131099658;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int bar = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int visitor = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
