#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Android_Demo.Resource", IsApplication=true)]

namespace Android_Demo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int alpha = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int rotate = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int scale = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int translate = 2130968579;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int white = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int yellow = 2131034113;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int border = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int face_ysj = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int shape = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int son = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08000e
			public const int MyButton = 2131230734;
			
			// aapt resource value: 0x7f080008
			public const int alter = 2131230728;
			
			// aapt resource value: 0x7f08000f
			public const int btnSendSMS1 = 2131230735;
			
			// aapt resource value: 0x7f080010
			public const int btnSendSMS2 = 2131230736;
			
			// aapt resource value: 0x7f080002
			public const int buttona = 2131230722;
			
			// aapt resource value: 0x7f080006
			public const int buttonalter = 2131230726;
			
			// aapt resource value: 0x7f080005
			public const int buttonr = 2131230725;
			
			// aapt resource value: 0x7f080003
			public const int buttons = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int buttont = 2131230724;
			
			// aapt resource value: 0x7f080009
			public const int faceImage = 2131230729;
			
			// aapt resource value: 0x7f08000c
			public const int iv1 = 2131230732;
			
			// aapt resource value: 0x7f08000d
			public const int iv2 = 2131230733;
			
			// aapt resource value: 0x7f080001
			public const int linearLayout1 = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int linearLayout2 = 2131230720;
			
			// aapt resource value: 0x7f080007
			public const int rl = 2131230727;
			
			// aapt resource value: 0x7f08000b
			public const int tvName = 2131230731;
			
			// aapt resource value: 0x7f08000a
			public const int tvWecomeEmp = 2131230730;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int bar = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int image = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int visitor = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int AppTheme = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int button_text = 2131165185;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
