#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CameraApp4.Resource", IsApplication=true)]

namespace CameraApp4
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int gradient_bg = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060006
			public const int btSave = 2131099654;
			
			// aapt resource value: 0x7f060011
			public const int iv_face = 2131099665;
			
			// aapt resource value: 0x7f06000c
			public const int open = 2131099660;
			
			// aapt resource value: 0x7f060008
			public const int personFace = 2131099656;
			
			// aapt resource value: 0x7f06000a
			public const int personName = 2131099658;
			
			// aapt resource value: 0x7f06000e
			public const int relativeLayout1 = 2131099662;
			
			// aapt resource value: 0x7f06000b
			public const int surfaceView1 = 2131099659;
			
			// aapt resource value: 0x7f06000f
			public const int sv_camera = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int sv_top = 2131099664;
			
			// aapt resource value: 0x7f060014
			public const int switch_cam = 2131099668;
			
			// aapt resource value: 0x7f060000
			public const int tableLayout1 = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int tableRow1 = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int tableRow2 = 2131099652;
			
			// aapt resource value: 0x7f06000d
			public const int take = 2131099661;
			
			// aapt resource value: 0x7f060009
			public const int textView1 = 2131099657;
			
			// aapt resource value: 0x7f060002
			public const int textView10 = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int tvDelay = 2131099653;
			
			// aapt resource value: 0x7f060003
			public const int tvServer = 2131099651;
			
			// aapt resource value: 0x7f060013
			public const int tv_name = 2131099667;
			
			// aapt resource value: 0x7f060012
			public const int tv_weclome = 2131099666;
			
			// aapt resource value: 0x7f060007
			public const int view1 = 2131099655;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int config = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int display = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int init = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int mainnew = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int visitor = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int camera_menu = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
